name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    
    - name: compile
      run: gcc teste_espacopelotempo.c -o test_espacopelotempo -lm && gcc espacopelotempo.c -o espacopelotempo -lm

    - name: execute_test
      run: ./test_espacopelotempo
      
    - name: execute
      run: ./espacopelotempo
      
    - name: mostrar o conteúdo do arquivo criado
      run: cat espacopelotempo.txt
